This function takes a list of matrices and multiplies the list

$3x3 * 2x3$ is an example of an incompatible matrix. The inner two numbers must be the same for the pair to be compatible.

In [25]:
import numpy as np

def multiply_matrices(xs):
    res = xs[0]

    for m in xs[1:]:
        if (res.shape[1] != m.shape[0]):
            print("Error:\n", res, "\nand\n", m, "\nare incompatible matrices.")
            return

        res = np.dot(res, m)

    return res


Error:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]] 
and
 [[1 1 1]] 
are incompatible matrices.


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

An example of compatible matrices

In [26]:
a = np.array([[1, 2, 3], # 3x3
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([[1, 2, 3], # 3x3
              [4, 5, 6],
              [7, 8, 9]])

xs = [a,b]
multiply_matrices(xs)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

An example of incompatible matrices

In [27]:
a = np.array([[1, 2, 3], # 3x3
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([[1, 2, 3], # 3x3
              [4, 5, 6],
              [7, 8, 9]])
c = np.array([[1, 1, 1]]) #1x3

xs = [a,b,c]
multiply_matrices(xs)

Error:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]] 
and
 [[1 1 1]] 
are incompatible matrices.
