In [0]:
import numpy as np

Problem 1

Using only numpy, implement the function conv2d. It takes as input input_mat and kernel_mat and outputs output_mat. All variables are square matrices. It should compute the convolution of input_mat with the kernel kernel_mat using valid padding.

Note that the size s of the kernel matrix can also be an even number.

In [0]:
def conv2d(input_mat, kernal_mat):
    in_size = input_mat.shape[0]
    k_size = kernal_mat.shape[0]

    # Check if matrices are valid.
    if input_mat.shape[0] != input_mat.shape[1]:
        print("Error: input matrix is not an n x n matrix.")
        return []
    elif kernal_mat.shape[0] != kernal_mat.shape[1]:
        print("Error: kernal matrix is not an n x n matrix.")
        return []
    elif k_size > in_size:
        print("Error: kernal matrix cannot be larger than input matrix.")
        return []
    
    n = in_size - k_size + 1
    if in_size < 1 or k_size < 1 or n < 1:
        print("Error: Negative dimensions are not allowed.");
        return []
    
    # Create output matrix
    output_mat = np.zeros((n, n))

    # Convolution
    for i in range(n):
        for j in range(n):
            output_mat[i, j] = np.sum(input_mat[i:i+k_size, j:j+k_size] * kernal_mat)

    return output_mat


Test Cases


In [8]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
    output_mat = []
  else:
    output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")

[[2 4 2]
 [4 2 4]
 [2 4 2]]
Correct output!

[[2 0 0]
 [0 2 0]
 [0 0 2]]
Correct output!

[[ 1 -1  0]
 [-1  1 -1]
 [ 0 -1  1]]
Correct output!

[[4]]
Correct output!

Error: kernal matrix cannot be larger than input matrix.
[]
Correct output!



Using only numpy, implement the function maxpooling2d. It takes as input input_mat and s and outputs output_mat. The variables input_mat and output_mat are square matrices and s is an integer. It should compute the maxpooling operation on input_mat using window of shape s times s.

In [0]:
def maxpooling2d(input_mat, s):
    in_size = input_mat.shape[0]

    # Check if matrices are valid.
    if input_mat.shape[0] != input_mat.shape[1]:
        print("Error: input matrix is not an n x n matrix.")
        return []
    
    # Create dimensions of output matrix
    x = int(input_mat.shape[0] / s)
    y = int(input_mat.shape[1] / s)
    
    # Create output matrix
    output_mat = np.zeros((x, y))

    # Maxpooling
    for i in range(x):
        for j in range(y):
            in_slice = input_mat[i*s:(i+1)*s, j*s:(j+1)*s]
            output_mat[i, j] = np.amax(in_slice)

    return output_mat

In [10]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                           [2, 4, 2, 1],
                           [1, 2, 4, 2],
                           [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                              [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                           [2, 4, 2, 1, 0, 3],
                           [1, 2, 4, 2, 4, 5],
                           [2, 1, 2, 1, 2, 1],
                           [1, 1, 2, 3, 1, 2],
                           [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
                     [2, 4, 5],
                     [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  #output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")


[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!
